name: gitleaks with checkout@v2

on: [push, pull_request, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'beta'
        fetch-depth: '0'
    - name: gitleaks-action
      uses: rheien/gitleaks-action@master
      with:
        config-path: rules.toml
